# Generated by Django 4.1.3 on 2022-11-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='pics')),
                ('intro', models.TextField()),
            ],
        ),
    ]
